language: go
go:
- '1.7'
install:
  - "go get -d -v ./..."
  - "go build -v ./..."
deploy:
  provider: releases
  api_key:
    secure: PcrghLCNaFw0zxOKv1UWjPdje6wqEjXi1Vh6yQiZIy44xMtLZOHS0i7TpUcFu9bZMlOwqmirHs/fEZ9MK5KTYOXC+PROHFdKM9mT91fs7TbTePw6hju9wt/fnk/ljnisnrO/RI6miCJSX8nzSzWs+fZi/2hhLFznMIyEZxtnYPflQ1eqdddWf8h/yrPMzC+MbSvbKUOoZvU2umrV9gKyxM5Mz/oGMcgI2mYM7xoaTtCT+VRTo9IY4lVjnKDfWGGlDVYJpgSTR33ZaVkUZgrjisk+6hHTBkRIpxzWBPjVfvJSyHvrtF1Qpz1PIzZukrEjk0vTAi1oIVx+x3gfnqFR9NPBvs61UZvAR0VMXw+P2D1+c5r77qryIxm0t3+pYTx/pt++ONCJ+tej4ORmKGUCtbQLIleBFRCZFGOlFtoG/PsrJNvwjjg46Md4VvfXmLlijam0ZL4H+yl9tq752syiHuwR4V/ZzM/wXfZZzwrCi4HBuVuUO651edjhvNzdXZuJqrle+h+z19o/czPQJjfNBukv3jxGpJyKsnHbIGdl6kR/4uROlwdhxoBmCBx0d91Pnh9Xvzf8yoUT21U6C39T5xN4tbaiDSrzYcK2eMFCkLm13QpuOzl8bylStEETzgSv2dxx1dotnmW07N4w6OespEFlTXXWZ+6Ej2J211GUu+w=
  file:
    - release/terraform-provider-amp-linux-amd64
    - release/terraform-provider-amp-linux-386
    - release/terraform-provider-amp-linux-arm
    - release/terraform-provider-amp-darwin-amd64
  skip_cleanup: true
  on:
    repo: lenfree/TERRAFORM-provider-amp
    tags: true
